name: ll
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.0.0

dependencies:
  path: ^1.9.0
  io: ^1.0.4

  collection: any
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

executables:
  lld: main
